/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class PhoneEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PhoneEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PhoneEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_PhoneEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pjsua2JNI.PhoneEvent_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pjsua2JNI.PhoneEvent_change_ownership(this, swigCPtr, true);
  }

  public void msg(String date, String type, int code, String msg) {
    pjsua2JNI.PhoneEvent_msg(swigCPtr, this, date, type, code, msg);
  }

  public PhoneEvent() {
    this(pjsua2JNI.new_PhoneEvent(), true);
    pjsua2JNI.PhoneEvent_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
