/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class PhoneConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PhoneConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PhoneConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_PhoneConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLoglevel(int value) {
    pjsua2JNI.PhoneConfig_loglevel_set(swigCPtr, this, value);
  }

  public int getLoglevel() {
    return pjsua2JNI.PhoneConfig_loglevel_get(swigCPtr, this);
  }

  public void setTransType(String value) {
    pjsua2JNI.PhoneConfig_transType_set(swigCPtr, this, value);
  }

  public String getTransType() {
    return pjsua2JNI.PhoneConfig_transType_get(swigCPtr, this);
  }

  public void setDelayBeforeRefreshSec(int value) {
    pjsua2JNI.PhoneConfig_delayBeforeRefreshSec_set(swigCPtr, this, value);
  }

  public int getDelayBeforeRefreshSec() {
    return pjsua2JNI.PhoneConfig_delayBeforeRefreshSec_get(swigCPtr, this);
  }

  public void setRetryIntervalSec(int value) {
    pjsua2JNI.PhoneConfig_retryIntervalSec_set(swigCPtr, this, value);
  }

  public int getRetryIntervalSec() {
    return pjsua2JNI.PhoneConfig_retryIntervalSec_get(swigCPtr, this);
  }

  public void setTimeoutSec(int value) {
    pjsua2JNI.PhoneConfig_timeoutSec_set(swigCPtr, this, value);
  }

  public int getTimeoutSec() {
    return pjsua2JNI.PhoneConfig_timeoutSec_get(swigCPtr, this);
  }

  public void setUdpKaIntervalSec(int value) {
    pjsua2JNI.PhoneConfig_udpKaIntervalSec_set(swigCPtr, this, value);
  }

  public int getUdpKaIntervalSec() {
    return pjsua2JNI.PhoneConfig_udpKaIntervalSec_get(swigCPtr, this);
  }

  public void setPort(long value) {
    pjsua2JNI.PhoneConfig_port_set(swigCPtr, this, value);
  }

  public long getPort() {
    return pjsua2JNI.PhoneConfig_port_get(swigCPtr, this);
  }

  public void setPortRange(int value) {
    pjsua2JNI.PhoneConfig_portRange_set(swigCPtr, this, value);
  }

  public int getPortRange() {
    return pjsua2JNI.PhoneConfig_portRange_get(swigCPtr, this);
  }

  public void setLl_api_server(String value) {
    pjsua2JNI.PhoneConfig_ll_api_server_set(swigCPtr, this, value);
  }

  public String getLl_api_server() {
    return pjsua2JNI.PhoneConfig_ll_api_server_get(swigCPtr, this);
  }

  public void setApi_key(String value) {
    pjsua2JNI.PhoneConfig_api_key_set(swigCPtr, this, value);
  }

  public String getApi_key() {
    return pjsua2JNI.PhoneConfig_api_key_get(swigCPtr, this);
  }

  public void setSdk_secret(String value) {
    pjsua2JNI.PhoneConfig_sdk_secret_set(swigCPtr, this, value);
  }

  public String getSdk_secret() {
    return pjsua2JNI.PhoneConfig_sdk_secret_get(swigCPtr, this);
  }

  public void setSeatId(String value) {
    pjsua2JNI.PhoneConfig_seatId_set(swigCPtr, this, value);
  }

  public String getSeatId() {
    return pjsua2JNI.PhoneConfig_seatId_get(swigCPtr, this);
  }

  public void setSeatPwd(String value) {
    pjsua2JNI.PhoneConfig_seatPwd_set(swigCPtr, this, value);
  }

  public String getSeatPwd() {
    return pjsua2JNI.PhoneConfig_seatPwd_get(swigCPtr, this);
  }

  public void setApp_name(String value) {
    pjsua2JNI.PhoneConfig_app_name_set(swigCPtr, this, value);
  }

  public String getApp_name() {
    return pjsua2JNI.PhoneConfig_app_name_get(swigCPtr, this);
  }

  public void setLogConfig(LogConfig value) {
    pjsua2JNI.PhoneConfig_logConfig_set(swigCPtr, this, LogConfig.getCPtr(value), value);
  }

  public LogConfig getLogConfig() {
    long cPtr = pjsua2JNI.PhoneConfig_logConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LogConfig(cPtr, false);
  }

  public void setPe(PhoneEvent value) {
    pjsua2JNI.PhoneConfig_pe_set(swigCPtr, this, PhoneEvent.getCPtr(value), value);
  }

  public PhoneEvent getPe() {
    long cPtr = pjsua2JNI.PhoneConfig_pe_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PhoneEvent(cPtr, false);
  }

  public PhoneConfig() {
    this(pjsua2JNI.new_PhoneConfig(), true);
  }

}
