/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class Phone {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Phone(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Phone obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_Phone(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Phone() {
    this(pjsua2JNI.new_Phone(), true);
  }

  public void logFunc(int level, String data, int len) {
    pjsua2JNI.Phone_logFunc(swigCPtr, this, level, data, len);
  }

  public void utilLogWrite(LogEntry entry) {
    pjsua2JNI.Phone_utilLogWrite(swigCPtr, this, LogEntry.getCPtr(entry), entry);
  }

  public void init(PhoneConfig pConfig) {
    pjsua2JNI.Phone_init(swigCPtr, this, PhoneConfig.getCPtr(pConfig), pConfig);
  }

  public void login() {
    pjsua2JNI.Phone_login(swigCPtr, this);
  }

  public void resetLoginCnt() {
    pjsua2JNI.Phone_resetLoginCnt(swigCPtr, this);
  }

  public void unInit() {
    pjsua2JNI.Phone_unInit(swigCPtr, this);
  }

  public void dialDTMF(String digits) {
    pjsua2JNI.Phone_dialDTMF(swigCPtr, this, digits);
  }

  public String callout(String dialCall) {
    return pjsua2JNI.Phone_callout__SWIG_0(swigCPtr, this, dialCall);
  }

  public String callout(String dialCall, String extend) {
    return pjsua2JNI.Phone_callout__SWIG_1(swigCPtr, this, dialCall, extend);
  }

  public String calloutParm(String dialCall, String extend) {
    return pjsua2JNI.Phone_calloutParm(swigCPtr, this, dialCall, extend);
  }

  public void dropCall() {
    pjsua2JNI.Phone_dropCall(swigCPtr, this);
  }

  public void answerCall() {
    pjsua2JNI.Phone_answerCall(swigCPtr, this);
  }

  public String https_post(String arg0, String arg1) {
    return pjsua2JNI.Phone_https_post(swigCPtr, this, arg0, arg1);
  }

  public String getTime() {
    return pjsua2JNI.Phone_getTime(swigCPtr, this);
  }

  public String getDate() {
    return pjsua2JNI.Phone_getDate(swigCPtr, this);
  }

  public String getVersion() {
    return pjsua2JNI.Phone_getVersion(swigCPtr, this);
  }

}
