/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class pjsua2JNI {
  public final static native void delete_PhoneEvent(long jarg1);
  public final static native void PhoneEvent_msg(long jarg1, PhoneEvent jarg1_, String jarg2, String jarg3, int jarg4, String jarg5);
  public final static native long new_PhoneEvent();
  public final static native void PhoneEvent_director_connect(PhoneEvent obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void PhoneEvent_change_ownership(PhoneEvent obj, long cptr, boolean take_or_release);
  public final static native void LogEntry_level_set(long jarg1, LogEntry jarg1_, int jarg2);
  public final static native int LogEntry_level_get(long jarg1, LogEntry jarg1_);
  public final static native void LogEntry_msg_set(long jarg1, LogEntry jarg1_, String jarg2);
  public final static native String LogEntry_msg_get(long jarg1, LogEntry jarg1_);
  public final static native void LogEntry_threadId_set(long jarg1, LogEntry jarg1_, int jarg2);
  public final static native int LogEntry_threadId_get(long jarg1, LogEntry jarg1_);
  public final static native void LogEntry_threadName_set(long jarg1, LogEntry jarg1_, String jarg2);
  public final static native String LogEntry_threadName_get(long jarg1, LogEntry jarg1_);
  public final static native long new_LogEntry();
  public final static native void delete_LogEntry(long jarg1);
  public final static native void delete_LogWriter(long jarg1);
  public final static native void LogWriter_write(long jarg1, LogWriter jarg1_, long jarg2, LogEntry jarg2_);
  public final static native long new_LogWriter();
  public final static native void LogWriter_director_connect(LogWriter obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void LogWriter_change_ownership(LogWriter obj, long cptr, boolean take_or_release);
  public final static native void LogConfig_msgLogging_set(long jarg1, LogConfig jarg1_, long jarg2);
  public final static native long LogConfig_msgLogging_get(long jarg1, LogConfig jarg1_);
  public final static native void LogConfig_level_set(long jarg1, LogConfig jarg1_, long jarg2);
  public final static native long LogConfig_level_get(long jarg1, LogConfig jarg1_);
  public final static native void LogConfig_consoleLevel_set(long jarg1, LogConfig jarg1_, long jarg2);
  public final static native long LogConfig_consoleLevel_get(long jarg1, LogConfig jarg1_);
  public final static native void LogConfig_decor_set(long jarg1, LogConfig jarg1_, long jarg2);
  public final static native long LogConfig_decor_get(long jarg1, LogConfig jarg1_);
  public final static native void LogConfig_filename_set(long jarg1, LogConfig jarg1_, String jarg2);
  public final static native String LogConfig_filename_get(long jarg1, LogConfig jarg1_);
  public final static native void LogConfig_fileFlags_set(long jarg1, LogConfig jarg1_, long jarg2);
  public final static native long LogConfig_fileFlags_get(long jarg1, LogConfig jarg1_);
  public final static native void LogConfig_writer_set(long jarg1, LogConfig jarg1_, long jarg2, LogWriter jarg2_);
  public final static native long LogConfig_writer_get(long jarg1, LogConfig jarg1_);
  public final static native long new_LogConfig();
  public final static native void delete_LogConfig(long jarg1);
  public final static native void PhoneConfig_loglevel_set(long jarg1, PhoneConfig jarg1_, int jarg2);
  public final static native int PhoneConfig_loglevel_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_transType_set(long jarg1, PhoneConfig jarg1_, String jarg2);
  public final static native String PhoneConfig_transType_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_delayBeforeRefreshSec_set(long jarg1, PhoneConfig jarg1_, int jarg2);
  public final static native int PhoneConfig_delayBeforeRefreshSec_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_retryIntervalSec_set(long jarg1, PhoneConfig jarg1_, int jarg2);
  public final static native int PhoneConfig_retryIntervalSec_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_timeoutSec_set(long jarg1, PhoneConfig jarg1_, int jarg2);
  public final static native int PhoneConfig_timeoutSec_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_udpKaIntervalSec_set(long jarg1, PhoneConfig jarg1_, int jarg2);
  public final static native int PhoneConfig_udpKaIntervalSec_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_port_set(long jarg1, PhoneConfig jarg1_, long jarg2);
  public final static native long PhoneConfig_port_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_portRange_set(long jarg1, PhoneConfig jarg1_, int jarg2);
  public final static native int PhoneConfig_portRange_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_ll_api_server_set(long jarg1, PhoneConfig jarg1_, String jarg2);
  public final static native String PhoneConfig_ll_api_server_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_api_key_set(long jarg1, PhoneConfig jarg1_, String jarg2);
  public final static native String PhoneConfig_api_key_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_sdk_secret_set(long jarg1, PhoneConfig jarg1_, String jarg2);
  public final static native String PhoneConfig_sdk_secret_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_seatId_set(long jarg1, PhoneConfig jarg1_, String jarg2);
  public final static native String PhoneConfig_seatId_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_seatPwd_set(long jarg1, PhoneConfig jarg1_, String jarg2);
  public final static native String PhoneConfig_seatPwd_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_app_name_set(long jarg1, PhoneConfig jarg1_, String jarg2);
  public final static native String PhoneConfig_app_name_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_logConfig_set(long jarg1, PhoneConfig jarg1_, long jarg2, LogConfig jarg2_);
  public final static native long PhoneConfig_logConfig_get(long jarg1, PhoneConfig jarg1_);
  public final static native void PhoneConfig_pe_set(long jarg1, PhoneConfig jarg1_, long jarg2, PhoneEvent jarg2_);
  public final static native long PhoneConfig_pe_get(long jarg1, PhoneConfig jarg1_);
  public final static native long new_PhoneConfig();
  public final static native void delete_PhoneConfig(long jarg1);
  public final static native long new_Phone();
  public final static native void delete_Phone(long jarg1);
  public final static native void Phone_logFunc(long jarg1, Phone jarg1_, int jarg2, String jarg3, int jarg4);
  public final static native void Phone_utilLogWrite(long jarg1, Phone jarg1_, long jarg2, LogEntry jarg2_);
  public final static native void Phone_init(long jarg1, Phone jarg1_, long jarg2, PhoneConfig jarg2_);
  public final static native void Phone_login(long jarg1, Phone jarg1_);
  public final static native void Phone_resetLoginCnt(long jarg1, Phone jarg1_);
  public final static native void Phone_unInit(long jarg1, Phone jarg1_);
  public final static native void Phone_dialDTMF(long jarg1, Phone jarg1_, String jarg2);
  public final static native String Phone_callout__SWIG_0(long jarg1, Phone jarg1_, String jarg2);
  public final static native String Phone_callout__SWIG_1(long jarg1, Phone jarg1_, String jarg2, String jarg3);
  public final static native String Phone_calloutParm(long jarg1, Phone jarg1_, String jarg2, String jarg3);
  public final static native void Phone_dropCall(long jarg1, Phone jarg1_);
  public final static native void Phone_answerCall(long jarg1, Phone jarg1_);
  public final static native String Phone_https_post(long jarg1, Phone jarg1_, String jarg2, String jarg3);
  public final static native String Phone_getTime(long jarg1, Phone jarg1_);
  public final static native String Phone_getDate(long jarg1, Phone jarg1_);
  public final static native String Phone_getVersion(long jarg1, Phone jarg1_);

  public static void SwigDirector_PhoneEvent_msg(PhoneEvent jself, String date, String type, int code, String msg) {
    jself.msg(date, type, code, msg);
  }
  public static void SwigDirector_LogWriter_write(LogWriter jself, long entry) {
    jself.write(new LogEntry(entry, false));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
